### ISSUE TITLE
Resolution correction

### ISSUE THREAD

**Issue by Curt-T** [crystalfontz/bmp_to_epaper#1]
The resolution for the 200x200 module is incorrect. 

  else if (enteredModule == "CFAP200200A00154")
  {
    gBits = 1;
    rBits = 0;
    yBits = 0;

    modWidth = 122;     // Should be 200
    modLength = 250;   // Should be 200
    reverseColor = false;
    leftToRight = false;
}

**Comment by trevinjorg** [comment]
Good catch, thanks for the notice. It's been fixed in Master.
